//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalDOAddressing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalDOAddressing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalDOAddressing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code *.
        /// </summary>
        internal static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g: 03, 017, 016, 019.
        /// </summary>
        internal static string AreaCodeFormat {
            get {
                return ResourceManager.GetString("AreaCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City *.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string CountyDistrict {
            get {
                return ResourceManager.GetString("CountyDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only english characters are allowed at this point, please erase the fields content to start typing on other language..
        /// </summary>
        internal static string EnglishRestrictionErrorMessage {
            get {
                return ResourceManager.GetString("EnglishRestrictionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only hebrew characters are allowed at this point, please erase the fields content to start typing on other language..
        /// </summary>
        internal static string HebrewRestrictionErrorMessage {
            get {
                return ResourceManager.GetString("HebrewRestrictionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island.
        /// </summary>
        internal static string Island {
            get {
                return ResourceManager.GetString("Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Help.
        /// </summary>
        internal static string PhoneHelp {
            get {
                return ResourceManager.GetString("PhoneHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number *.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: 9-10 numbers.
        /// </summary>
        internal static string PhoneNumberFormat {
            get {
                return ResourceManager.GetString("PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code *.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:  4 numbers no spaces.
        /// </summary>
        internal static string PostalCodeFormat {
            get {
                return ResourceManager.GetString("PostalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefecture.
        /// </summary>
        internal static string Prefecture {
            get {
                return ResourceManager.GetString("Prefecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care of Name *.
        /// </summary>
        internal static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only rusian characters are allowed at this point, please erase the fields content to start typing on other language..
        /// </summary>
        internal static string RusianRestrictionErrorMessage {
            get {
                return ResourceManager.GetString("RusianRestrictionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Spacer {
            get {
                return ResourceManager.GetString("Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State *.
        /// </summary>
        internal static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street *.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 1 *.
        /// </summary>
        internal static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 2.
        /// </summary>
        internal static string Street2 {
            get {
                return ResourceManager.GetString("Street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 3.
        /// </summary>
        internal static string Street3 {
            get {
                return ResourceManager.GetString("Street3", resourceCulture);
            }
        }
    }
}
