using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyHerbalife3.Ordering.Providers.EventHandling
{
    public enum MyHLEventTypes
    {
        Unknown,
        APFChanged,
        CreditCardProcessing,
        CreditCardProcessed,
        CreditCardBillingAddressProcessing,
        CreditCardDeleting,
        CreditCardAuthorizationCompleted,
        CreditCardAuthenticationCompleted,
        PaymentInfoSaved,
        PaymentInfoCreated,
        PaymentInfoChanged,
        PaymentInfoDeleted,
        ShoppingCartChanged,
        ShoppingCartBeingCreated,
        ShoppingCartCreated,
        ShoppingCartRecalculated,
        ShoppingCartRetrieved,
        ShoppingCartBeingSaved,
        ShoppingCartSaved,
        ShoppingCartItemsBeingAdded,
        ShoppingCartItemsAdded,
        ShoppingCartItemsBeingRemoved,
        ShoppingCartItemsRemoved,
        ShoppingCartBeingDeleted,
        ShoppingCartDeleted,
        ShippingAddressCreated,
        ShippingAddressBeingCreated,
        ShippingAddressChanged,
        ShippingAddressBeingChanged,
        ShippingAddressDeleted,
        ShippingAddressBeingDeleted,
        PickupPreferenceCreated,
        PickupPreferenceBeingCreated,
        PickupPreferenceDeleted,
        PickupPreferenceBeingDeleted,
        ShippingAddressPopupClosed,
        ShippingAddressPopupCancelled,
        ShippingMethodChanged,
        OrderMonthChanged,
        QuoteRetrieved,
        QuoteError,
        OrderTypeChanged,
        CrossSellFound,
        NoCrossSellFound,
        ShowAllInventory,
        ShowAvailableInventory,
        ShippingInfoNotFilled,
        DeliveryOptionChanged,
        DeliveryOptionTypeSelected,
        DeliveryOptionTypeChanged,
        OrderSubTypeChanged,
        ProceedingToCheckout,
        ProceedingToSubmitOrder,
        PageVisitRefused,
        WarehouseChanged,
        PickUpOptionNotPopulated,
        NotifyTodaysMagazineAddressChanged,
        NotifyTodaysMagazineRecalculate,
        PickUpNicknameNotSelected,
        ProceedingToCheckoutFromMiniCart,
        PickUpNicknameNotSelectedInMiniCart,
        ProductAvailabilityTypeChanged,
        ProductDetailBeingLaunched,
        ProductDetailBeingClosed,
        ShowBackorderMessages,
        NotifyTodaysMagazineCancelOrder,
        ItemRemovedAPFLeft,
        CheckoutToShoppingCart,
        ShippingOptionNotPopulated,
        CheckOutOptionsNotPopulated,
        CartItemRemovedDueToSKULimitationRules,
        PaymentOptionsViewChanged,
        AddressNeedCorrected,
        OnStandAloneDonation,
        OnStandAloneDonationClear,
        OnSCancelDonationsVisible,
        ShippingMethodCheckVP,
        /// <summary>
        /// Event type for China DO - ShoppingCart Recalculated
        /// </summary>
        CNShoppingCartRecalculated,
        OnSaveCart,
        OnPaymentGatewayChanged
    }
}
