//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/Service/AddressValidation", ConfigurationName="AddressValidationSvc.AddressValidation_PortType")]
    public interface AddressValidation_PortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://herbalife.com/AddressServices/Service/AddressValidation/ValidateAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse1 ValidateAddress(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://herbalife.com/AddressServices/Service/AddressValidation/ValidateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse1> ValidateAddressAsync(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/Service/AddressValidation")]
    public partial class ValidateAddressRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReturnSuggestions returnSuggestionsField;
        
        private Address addressField;
        
        private UseSuggestedFirstLine useSuggestedFirstLineField;
        
        private UseSuggestedLastLine useSuggestedLastLineField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=0)]
        public ReturnSuggestions ReturnSuggestions {
            get {
                return this.returnSuggestionsField;
            }
            set {
                this.returnSuggestionsField = value;
                this.RaisePropertyChanged("ReturnSuggestions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=1)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=2)]
        public UseSuggestedFirstLine UseSuggestedFirstLine {
            get {
                return this.useSuggestedFirstLineField;
            }
            set {
                this.useSuggestedFirstLineField = value;
                this.RaisePropertyChanged("UseSuggestedFirstLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=3)]
        public UseSuggestedLastLine UseSuggestedLastLine {
            get {
                return this.useSuggestedLastLineField;
            }
            set {
                this.useSuggestedLastLineField = value;
                this.RaisePropertyChanged("UseSuggestedLastLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class ReturnSuggestions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maxCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string MaxCount {
            get {
                return this.maxCountField;
            }
            set {
                this.maxCountField = value;
                this.RaisePropertyChanged("MaxCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string line4Field;
        
        private string cityField;
        
        private string stateProvinceTerritoryField;
        
        private string countyDistrictField;
        
        private string countyCodeField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
                this.RaisePropertyChanged("Line1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
                this.RaisePropertyChanged("Line2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
                this.RaisePropertyChanged("Line3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
                this.RaisePropertyChanged("Line4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StateProvinceTerritory {
            get {
                return this.stateProvinceTerritoryField;
            }
            set {
                this.stateProvinceTerritoryField = value;
                this.RaisePropertyChanged("StateProvinceTerritory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CountyDistrict {
            get {
                return this.countyDistrictField;
            }
            set {
                this.countyDistrictField = value;
                this.RaisePropertyChanged("CountyDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class UseSuggestedFirstLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string primaryRangeValueField;
        
        private string secondaryRangeValueField;
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrimaryRangeValue {
            get {
                return this.primaryRangeValueField;
            }
            set {
                this.primaryRangeValueField = value;
                this.RaisePropertyChanged("PrimaryRangeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecondaryRangeValue {
            get {
                return this.secondaryRangeValueField;
            }
            set {
                this.secondaryRangeValueField = value;
                this.RaisePropertyChanged("SecondaryRangeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class UseSuggestedLastLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/Service/AddressValidation")]
    public partial class ValidateAddressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ValidationResult validationResultField;
        
        private Address addressField;
        
        private FirstLineSuggestion[] firstLineSuggestionsField;
        
        private LastLineSuggestion[] lastLineSuggestionsField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=0)]
        public ValidationResult ValidationResult {
            get {
                return this.validationResultField;
            }
            set {
                this.validationResultField = value;
                this.RaisePropertyChanged("ValidationResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=1)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FirstLineSuggestion", IsNullable=false)]
        public FirstLineSuggestion[] FirstLineSuggestions {
            get {
                return this.firstLineSuggestionsField;
            }
            set {
                this.firstLineSuggestionsField = value;
                this.RaisePropertyChanged("FirstLineSuggestions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LastLineSuggestion", IsNullable=false)]
        public LastLineSuggestion[] LastLineSuggestions {
            get {
                return this.lastLineSuggestionsField;
            }
            set {
                this.lastLineSuggestionsField = value;
                this.RaisePropertyChanged("LastLineSuggestions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class ValidationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string errorCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class FirstLineSuggestion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FirstLineSuggestionPrimaryRange primaryRangeField;
        
        private string preDirectionalField;
        
        private string primaryNameField;
        
        private string postDirectionalField;
        
        private string suffixField;
        
        private string secondaryNameField;
        
        private string unitTypeField;
        
        private FirstLineSuggestionSecondaryRange secondaryRangeField;
        
        private string postalCodeField;
        
        private FirstLineSuggestionPostalCodeExtension[] postalCodeExtensionField;
        
        private FirstLineSuggestionCarrierRoute[] carrierRouteField;
        
        private string countyCodeField;
        
        private string identifierField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FirstLineSuggestionPrimaryRange PrimaryRange {
            get {
                return this.primaryRangeField;
            }
            set {
                this.primaryRangeField = value;
                this.RaisePropertyChanged("PrimaryRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PreDirectional {
            get {
                return this.preDirectionalField;
            }
            set {
                this.preDirectionalField = value;
                this.RaisePropertyChanged("PreDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrimaryName {
            get {
                return this.primaryNameField;
            }
            set {
                this.primaryNameField = value;
                this.RaisePropertyChanged("PrimaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostDirectional {
            get {
                return this.postDirectionalField;
            }
            set {
                this.postDirectionalField = value;
                this.RaisePropertyChanged("PostDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
                this.RaisePropertyChanged("Suffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SecondaryName {
            get {
                return this.secondaryNameField;
            }
            set {
                this.secondaryNameField = value;
                this.RaisePropertyChanged("SecondaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public FirstLineSuggestionSecondaryRange SecondaryRange {
            get {
                return this.secondaryRangeField;
            }
            set {
                this.secondaryRangeField = value;
                this.RaisePropertyChanged("SecondaryRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostalCodeExtension", Order=9)]
        public FirstLineSuggestionPostalCodeExtension[] PostalCodeExtension {
            get {
                return this.postalCodeExtensionField;
            }
            set {
                this.postalCodeExtensionField = value;
                this.RaisePropertyChanged("PostalCodeExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CarrierRoute", Order=10)]
        public FirstLineSuggestionCarrierRoute[] CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class FirstLineSuggestionPrimaryRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lowField;
        
        private string highField;
        
        private string appliesToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
                this.RaisePropertyChanged("Low");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
                this.RaisePropertyChanged("High");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
                this.RaisePropertyChanged("AppliesTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class FirstLineSuggestionSecondaryRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lowField;
        
        private string highField;
        
        private string appliesToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
                this.RaisePropertyChanged("Low");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
                this.RaisePropertyChanged("High");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
                this.RaisePropertyChanged("AppliesTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class FirstLineSuggestionPostalCodeExtension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appliesToField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
                this.RaisePropertyChanged("AppliesTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class FirstLineSuggestionCarrierRoute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appliesToField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
                this.RaisePropertyChanged("AppliesTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.herbalife.com/AddressServices/V02/AddressServices")]
    public partial class LastLineSuggestion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string stateProvinceTerritoryField;
        
        private string postalCodeField;
        
        private string identifierField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateProvinceTerritory {
            get {
                return this.stateProvinceTerritoryField;
            }
            set {
                this.stateProvinceTerritoryField = value;
                this.RaisePropertyChanged("StateProvinceTerritory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAddressRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/Service/AddressValidation", Order=0)]
        public MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest ValidateAddressRequest;
        
        public ValidateAddressRequest1() {
        }
        
        public ValidateAddressRequest1(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest ValidateAddressRequest) {
            this.ValidateAddressRequest = ValidateAddressRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAddressResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.herbalife.com/AddressServices/V02/Service/AddressValidation", Order=0)]
        public MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse ValidateAddressResponse;
        
        public ValidateAddressResponse1() {
        }
        
        public ValidateAddressResponse1(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse ValidateAddressResponse) {
            this.ValidateAddressResponse = ValidateAddressResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressValidation_PortTypeChannel : MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.AddressValidation_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressValidation_PortTypeClient : System.ServiceModel.ClientBase<MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.AddressValidation_PortType>, MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.AddressValidation_PortType {
        
        public AddressValidation_PortTypeClient() {
        }
        
        public AddressValidation_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressValidation_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressValidation_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressValidation_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse1 ValidateAddress(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest1 request) {
            return base.Channel.ValidateAddress(request);
        }
        
        public System.Threading.Tasks.Task<MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressResponse1> ValidateAddressAsync(MyHerbalife3.Ordering.ServiceProvider.AddressValidationSvc.ValidateAddressRequest1 request) {
            return base.Channel.ValidateAddressAsync(request);
        }
    }
}
