//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyHL_ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyHL_ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MyHL_ErrorMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HFF was not added to the cart..
        /// </summary>
        internal static string AddHFFFailed {
            get {
                return ResourceManager.GetString("AddHFFFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully added HFF to the cart..
        /// </summary>
        internal static string AddHFFSucceeded {
            get {
                return ResourceManager.GetString("AddHFFSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add an amount greater than 0..
        /// </summary>
        internal static string AddHFFZero {
            get {
                return ResourceManager.GetString("AddHFFZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address confirmation is required.
        /// </summary>
        internal static string AddressConfirmationRequired {
            get {
                return ResourceManager.GetString("AddressConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address already exists in the database test.
        /// </summary>
        internal static string AddressExists {
            get {
                return ResourceManager.GetString("AddressExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today magazine has been added to the cart..
        /// </summary>
        internal static string AddTodayMagazine {
            get {
                return ResourceManager.GetString("AddTodayMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number..
        /// </summary>
        internal static string AddTodayMagazineEnterNumber {
            get {
                return ResourceManager.GetString("AddTodayMagazineEnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit for Today Magazine is .
        /// </summary>
        internal static string AddTodayMagazineMax {
            get {
                return ResourceManager.GetString("AddTodayMagazineMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of magazines that can be added to cart is {0}..
        /// </summary>
        internal static string AddTodayMagazineMaXQuantity {
            get {
                return ResourceManager.GetString("AddTodayMagazineMaXQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Annual Processing Fee is due, we&apos;ll add into your shopping cart automatically..
        /// </summary>
        internal static string APFDue {
            get {
                return ResourceManager.GetString("APFDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Annual Processing Fees are due. They have been added to your cart..
        /// </summary>
        internal static string APFDueAdded {
            get {
                return ResourceManager.GetString("APFDueAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APF is due on {0}.
        /// </summary>
        internal static string APFDueDateNotification {
            get {
                return ResourceManager.GetString("APFDueDateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT: {0} years of APF is due and must be paid before placing a &quot;Resale&quot; type order. Please change your order type to &quot;Personal&quot; to pay for your APF..
        /// </summary>
        internal static string APFdueResaleNotAllowed {
            get {
                return ResourceManager.GetString("APFdueResaleNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Annual Membership Services Fee is due on {0}. In order to prevent any interruptions, please pay the Annual Membership Services Fee before or on the due date..
        /// </summary>
        internal static string APFFeeDueFuturePopup {
            get {
                return ResourceManager.GetString("APFFeeDueFuturePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Annual Membership Services Fee was due on {0}. In order to prevent any interruption to your business, please pay the Annual Membership Services Fee as soon as possible..
        /// </summary>
        internal static string APFFeeDuePastPopup {
            get {
                return ResourceManager.GetString("APFFeeDuePastPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Annual Membership Services Fee is due Today. In order to prevent any interruptions, please pay the Annual Membership Services Fee today..
        /// </summary>
        internal static string APFFeeDueTodayPopup {
            get {
                return ResourceManager.GetString("APFFeeDueTodayPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the APF quantity you would like to purchase between 1 and {0}..
        /// </summary>
        internal static string APFinvalidQtyDsLevel {
            get {
                return ResourceManager.GetString("APFinvalidQtyDsLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code:.
        /// </summary>
        internal static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorization Code:.
        /// </summary>
        internal static string AutorizationCode {
            get {
                return ResourceManager.GetString("AutorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SKU {0} added will be on back order..
        /// </summary>
        internal static string BackOrderItem {
            get {
                return ResourceManager.GetString("BackOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For item {0} only a quantity of {1} is available. Please amend the quantity entered to add this item to your cart..
        /// </summary>
        internal static string BackOrderNotAllowedPartialQuantity {
            get {
                return ResourceManager.GetString("BackOrderNotAllowedPartialQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For item {0}, a quantity of {1} is available and a quantity of {2} will be available for a backorder..
        /// </summary>
        internal static string BackOrderPartialQuantity {
            get {
                return ResourceManager.GetString("BackOrderPartialQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlockAmexCard {
            get {
                return ResourceManager.GetString("BlockAmexCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to complete your order. Please contact Distributor Relations for assistance (866) 866-4744 and mention error code 05..
        /// </summary>
        internal static string BlockedDS {
            get {
                return ResourceManager.GetString("BlockedDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to complete your order. Please contact Distributor Relations for assistance (866) 866-4744 and mention error code 01..
        /// </summary>
        internal static string BlockedZip {
            get {
                return ResourceManager.GetString("BlockedZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note:&lt;br/&gt;This site is best viewed with Internet Explorer or Firefox..
        /// </summary>
        internal static string BrowserCompatibilityWarning {
            get {
                return ResourceManager.GetString("BrowserCompatibilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this order? Clicking &quot;OK&quot; will remove all items from your cart..
        /// </summary>
        internal static string CancelOrderConfirmation {
            get {
                return ResourceManager.GetString("CancelOrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APF skus cannot be added to your cart.
        /// </summary>
        internal static string CannotAddAPFSku {
            get {
                return ResourceManager.GetString("CannotAddAPFSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APF skus cannot be removed to your cart.
        /// </summary>
        internal static string CannotRemoveAPFSku {
            get {
                return ResourceManager.GetString("CannotRemoveAPFSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only prepay one year of APF..
        /// </summary>
        internal static string CanOnlyPrepayOneAPF {
            get {
                return ResourceManager.GetString("CanOnlyPrepayOneAPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to process your request, please contact Distributor Service at -country’s phone number-..
        /// </summary>
        internal static string CantBuy {
            get {
                return ResourceManager.GetString("CantBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: Your buying privileges are currently on hold until the required “Protecting Your Business 101” training is completed. If you wish to complete the training now, 
        ///please click on the following link:  &lt;a href=&quot;http://10.36.174.134/toolsAndTraining/business/Training/protectingYourBusiness101.htm&quot; target=&quot;_blank&quot;&gt;Link&lt;/a&gt;.
        /// </summary>
        internal static string CantBuyBecauseofTraining {
            get {
                return ResourceManager.GetString("CantBuyBecauseofTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID is not acceptable. Please contact local Distributor Services Hotline..
        /// </summary>
        internal static string CantOrder {
            get {
                return ResourceManager.GetString("CantOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t purchase..
        /// </summary>
        internal static string CantPurchase {
            get {
                return ResourceManager.GetString("CantPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot go to the {0} page with no items in your cart..
        /// </summary>
        internal static string CantVisitWithEmptyCart {
            get {
                return ResourceManager.GetString("CantVisitWithEmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Shipping or Pickup option to proceed..
        /// </summary>
        internal static string CantVisitWithNoDeliveryInfo {
            get {
                return ResourceManager.GetString("CantVisitWithNoDeliveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can no longer use this card due to multiple declines.
        /// </summary>
        internal static string CardExceededAllowedDeclines {
            get {
                return ResourceManager.GetString("CardExceededAllowedDeclines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit card will expire within the next 30 days. Please update your payment information..
        /// </summary>
        internal static string CardExpirationWarning {
            get {
                return ResourceManager.GetString("CardExpirationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit card is expired. Please contact local Distributor Service Hotline..
        /// </summary>
        internal static string CardExpired {
            get {
                return ResourceManager.GetString("CardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit card is expired. Please click Edit and update the expiration date..
        /// </summary>
        internal static string CardExpiredForSavedCard {
            get {
                return ResourceManager.GetString("CardExpiredForSavedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Credit Card has expired. Please update your payment information..
        /// </summary>
        internal static string CardExpiredForSavedCardHAP {
            get {
                return ResourceManager.GetString("CardExpiredForSavedCardHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was declined for this card.
        /// </summary>
        internal static string CardWasDeclined {
            get {
                return ResourceManager.GetString("CardWasDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Yes/No..
        /// </summary>
        internal static string CasaCheckRequired {
            get {
                return ResourceManager.GetString("CasaCheckRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter donation amount, except zero(0)..
        /// </summary>
        internal static string CasaDonationRequired {
            get {
                return ResourceManager.GetString("CasaDonationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have backorder items in your cart that will be removed if you select pickup as your shipping option. Do you wish to continue? (&quot;Yes&quot; or &quot;No&quot;).
        /// </summary>
        internal static string ChangeToPUwithBackOrderItemsinCart {
            get {
                return ResourceManager.GetString("ChangeToPUwithBackOrderItemsinCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Chinese Character Allowed.
        /// </summary>
        internal static string ChineseCharacterOnly {
            get {
                return ResourceManager.GetString("ChineseCharacterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name is too long.
        /// </summary>
        internal static string CityTooLong {
            get {
                return ResourceManager.GetString("CityTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have product(s) in your shopping cart. Do you want to clear your cart before proceed to purchase event tickets?.
        /// </summary>
        internal static string ClearCart {
            get {
                return ResourceManager.GetString("ClearCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your annual fee purchase before adding other products to cart..
        /// </summary>
        internal static string CompleteAPFPurchase {
            get {
                return ResourceManager.GetString("CompleteAPFPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You will not be able to place an order, Only Korean distributors can purchase orders from Korea website..
        /// </summary>
        internal static string CountryOfProcessingOnly {
            get {
                return ResourceManager.GetString("CountryOfProcessingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. The currency could not be converted.please contact the distributor service hotline 080-906-7070..
        /// </summary>
        internal static string CurrencyConversionFailed {
            get {
                return ResourceManager.GetString("CurrencyConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the CVV..
        /// </summary>
        internal static string CVVMissing {
            get {
                return ResourceManager.GetString("CVVMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter a new credit card or correct the existing ones.
        /// </summary>
        internal static string DisplayCCLink {
            get {
                return ResourceManager.GetString("DisplayCCLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a valid Credit Card on file..
        /// </summary>
        internal static string DisplayCCMessage {
            get {
                return ResourceManager.GetString("DisplayCCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online ordering is not allowed..
        /// </summary>
        internal static string DONotAllowed {
            get {
                return ResourceManager.GetString("DONotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online order is not available..
        /// </summary>
        internal static string DONotAvailable {
            get {
                return ResourceManager.GetString("DONotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name is already used, please enter a different name..
        /// </summary>
        internal static string DuplicateAddressNickname {
            get {
                return ResourceManager.GetString("DuplicateAddressNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add the same card more than once..
        /// </summary>
        internal static string DuplicateCardError {
            get {
                return ResourceManager.GetString("DuplicateCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A card with number {0} is already registered. If you wish to modify this card&apos;s data, please select the edit option.
        /// </summary>
        internal static string DuplicatedCardNumberError {
            get {
                return ResourceManager.GetString("DuplicatedCardNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your previous order was already submitted prior to the changes that were made to your cart. Your order number is {0}. You can verify the status of this order by calling Order Support at 1-866-866-4744, 9 a.m. to 6 p.m. PST, Monday - Friday. Saturday 6 a.m. to 2 p.m. PST for assistance or by clicking here. (Please note that it may take up to 1 hour before the order is displayed.&lt;br&gt;If you would like to place a new order, please re-add items to your cart..
        /// </summary>
        internal static string DuplicateOrder {
            get {
                return ResourceManager.GetString("DuplicateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique pickuplocation..
        /// </summary>
        internal static string DuplicatePickupLocation {
            get {
                return ResourceManager.GetString("DuplicatePickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate SKU has been entered. Please re-enter..
        /// </summary>
        internal static string DuplicateSKU {
            get {
                return ResourceManager.GetString("DuplicateSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not add the item(s) to the cart since by adding them into the cart, you exceed your earnings limit..
        /// </summary>
        internal static string EarningsExceeds {
            get {
                return ResourceManager.GetString("EarningsExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to cancel your order. Please call Distributor Services at  080-906-7070..
        /// </summary>
        internal static string ErrorCancelHAPOrder {
            get {
                return ResourceManager.GetString("ErrorCancelHAPOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ticket Purchases are not allowed on this site..
        /// </summary>
        internal static string EventPurchasingNotAvailable {
            get {
                return ResourceManager.GetString("EventPurchasingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your annual fee purchase before purchasing event tickets..
        /// </summary>
        internal static string EventTicketCompleteAPF {
            get {
                return ResourceManager.GetString("EventTicketCompleteAPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have event ticket items in your cart, do you want to clear your cart?.
        /// </summary>
        internal static string EventTicketInCart {
            get {
                return ResourceManager.GetString("EventTicketInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ticket purchases are limited to quantity of {0} per order..
        /// </summary>
        internal static string EventTicketsLimitedQuantity {
            get {
                return ResourceManager.GetString("EventTicketsLimitedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Note that Extravaganza merchandise cannot be combined with regular product orders..
        /// </summary>
        internal static string ExtravaganzaStandaloneOrder {
            get {
                return ResourceManager.GetString("ExtravaganzaStandaloneOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Payment Transaction for your Order was not authorized, if case of doubt, please contact the Distributor Services Department (11-3879-7844)..
        /// </summary>
        internal static string FControlDeclined {
            get {
                return ResourceManager.GetString("FControlDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data format error, please enter the correct data..
        /// </summary>
        internal static string GeneralInputError {
            get {
                return ResourceManager.GetString("GeneralInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Homepage..
        /// </summary>
        internal static string GotoHomePage {
            get {
                return ResourceManager.GetString("GotoHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literature and Promotional type items may not be  added to HAP Standing Order..
        /// </summary>
        internal static string HAPOrderAddingNonProducts {
            get {
                return ResourceManager.GetString("HAPOrderAddingNonProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be added to your cart because Ordered Quantity cannot exceed the limit of 6 items per SKU.  Please edit the quantity..
        /// </summary>
        internal static string HAPOrderExceedSKU {
            get {
                return ResourceManager.GetString("HAPOrderExceedSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be added to your cart because Ordered Quantity cannot exceed the limit of 4 items per SKU.  Please edit the quantity..
        /// </summary>
        internal static string HAPOrderExceedSKUForMember {
            get {
                return ResourceManager.GetString("HAPOrderExceedSKUForMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items could not be added to your cart because your order exceeds the allowable 1000 Volume Point limit for Personal HAP orders. Please review your order..
        /// </summary>
        internal static string HAPOrderExceedVP {
            get {
                return ResourceManager.GetString("HAPOrderExceedVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items could not be added to your cart because your order exceeds the allowable 1000 Points limit for Personal HAP orders. Please review your order..
        /// </summary>
        internal static string HAPOrderExceedVPForMB {
            get {
                return ResourceManager.GetString("HAPOrderExceedVPForMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your HAP orders are due please Renew.
        /// </summary>
        internal static string HAPOrderExpired {
            get {
                return ResourceManager.GetString("HAPOrderExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is below the minimum 100 Volume Point required for a HAP order.  Please add additional items to your order..
        /// </summary>
        internal static string HAPOrderLessVP {
            get {
                return ResourceManager.GetString("HAPOrderLessVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is below the minimum 100 Points required for a HAP order.  Please add additional items to your order..
        /// </summary>
        internal static string HAPOrderLessVPForMB {
            get {
                return ResourceManager.GetString("HAPOrderLessVPForMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your order is exceeding 2000PPV, as per our records we have not received your FBO registration details, hence we are unable to accept your order for more than 2000PPV this month.  As per FSSAI any food business operator like you needs to obtain FBO Registration or license and submit a copy to Herbalife. For additional information and assistance with applying for the necessary documents (if you believe you will exceed the limit), visit Myherbalife.com upon completing your online registration or contact Asso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndiaFSSAIMessage {
            get {
                return ResourceManager.GetString("IndiaFSSAIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill area code in proper format..
        /// </summary>
        internal static string InvalidAreaCode {
            get {
                return ResourceManager.GetString("InvalidAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid city..
        /// </summary>
        internal static string InvalidCity {
            get {
                return ResourceManager.GetString("InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid date. Sunday is invalid for pickup/delivery..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill extension in proper format..
        /// </summary>
        internal static string InvalidExtension {
            get {
                return ResourceManager.GetString("InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid First Name..
        /// </summary>
        internal static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Min 4 Characters - Alphanumeric in HKID field without any space.
        /// </summary>
        internal static string InvalidHKID {
            get {
                return ResourceManager.GetString("InvalidHKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid LastName..
        /// </summary>
        internal static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid MiddleName..
        /// </summary>
        internal static string InvalidMiddleName {
            get {
                return ResourceManager.GetString("InvalidMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Nickname..
        /// </summary>
        internal static string InvalidNickname {
            get {
                return ResourceManager.GetString("InvalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill phone number in proper format..
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Name..
        /// </summary>
        internal static string InvalidRecipentName {
            get {
                return ResourceManager.GetString("InvalidRecipentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify correct RG Number.
        /// </summary>
        internal static string InvalidRGNumberSelected {
            get {
                return ResourceManager.GetString("InvalidRGNumberSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review your shipping address, the current one is not valid..
        /// </summary>
        internal static string InvalidShippingAddress {
            get {
                return ResourceManager.GetString("InvalidShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SKU {0} is invalid..
        /// </summary>
        internal static string InvalidSKU {
            get {
                return ResourceManager.GetString("InvalidSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill SMS Mobile Number in proper format..
        /// </summary>
        internal static string InvalidSMSNumber {
            get {
                return ResourceManager.GetString("InvalidSMSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state is invalid..
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street address should contain atleast one number one space and one alphabet..
        /// </summary>
        internal static string InvalidStreetAddress {
            get {
                return ResourceManager.GetString("InvalidStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street address should contain atleast one alphabet..
        /// </summary>
        internal static string InvalidStreetAddress2 {
            get {
                return ResourceManager.GetString("InvalidStreetAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid address with out using &lt;,&gt; &quot; &quot; and %.
        /// </summary>
        internal static string InvalidStreetAddressSpecialCharacters {
            get {
                return ResourceManager.GetString("InvalidStreetAddressSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip code is not valid..
        /// </summary>
        internal static string InvalidZipCode {
            get {
                return ResourceManager.GetString("InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to browse product without placing an order, you won&apos;t be able to add product to the cart..
        /// </summary>
        internal static string JustBrowse {
            get {
                return ResourceManager.GetString("JustBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact Member Business Practice and Compliance at (310)216-6056.
        /// </summary>
        internal static string KountDeclinedOrder {
            get {
                return ResourceManager.GetString("KountDeclinedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive the latest status of this order, please visit  &lt;a href=&quot;/account/pendingorders&quot; target=&quot;_self&quot;&gt;My Orders&lt;/a&gt;..
        /// </summary>
        internal static string KountReviewOrder {
            get {
                return ResourceManager.GetString("KountReviewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently not enough inventory for item {0}. Available quantity {1}..
        /// </summary>
        internal static string LessInventory {
            get {
                return ResourceManager.GetString("LessInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shipping information is no longer valid, shopping cart will be cleared..
        /// </summary>
        internal static string LocationNotValid {
            get {
                return ResourceManager.GetString("LocationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your ID and PIN # and try again. If you continue to face issues please contact the Distributor Service hotline..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that you can only save card details for a maximum of {0} cards. In order to add a new card, please remove one of your existing saved cards..
        /// </summary>
        internal static string MaxCardsToDisplay {
            get {
                return ResourceManager.GetString("MaxCardsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU {0} : Quantity can&apos;t be larger than {1}..
        /// </summary>
        internal static string MaxQuantity {
            get {
                return ResourceManager.GetString("MaxQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum up to {0} tickets per membership for primary member and/ or  spouse / partner..
        /// </summary>
        internal static string MaxQuantityETO {
            get {
                return ResourceManager.GetString("MaxQuantityETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  HAP Deadline date.
        /// </summary>
        internal static string MissingHapDate {
            get {
                return ResourceManager.GetString("MissingHapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select HAP Order Type: Personal Consumption or Resale and HAP Deadline date.
        /// </summary>
        internal static string MissingHapType {
            get {
                return ResourceManager.GetString("MissingHapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Invoice option..
        /// </summary>
        internal static string MissingInvoiceOption {
            get {
                return ResourceManager.GetString("MissingInvoiceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have event ticket items in your cart, do you want to clear your cart?.
        /// </summary>
        internal static string MustCheckout {
            get {
                return ResourceManager.GetString("MustCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must delete one of your credit cards to change the items in your cart..
        /// </summary>
        internal static string MustDeleteACardToChangeItemsInCart {
            get {
                return ResourceManager.GetString("MustDeleteACardToChangeItemsInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Express Company.
        /// </summary>
        internal static string NeedExpressCompany {
            get {
                return ResourceManager.GetString("NeedExpressCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Order Type from the mini cart.
        /// </summary>
        internal static string NeedToSelectOrderType {
            get {
                return ResourceManager.GetString("NeedToSelectOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the area code..
        /// </summary>
        internal static string NoAreaCode {
            get {
                return ResourceManager.GetString("NoAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backorder should be allowed for deliveries to New Caledonia and French Polynesia..
        /// </summary>
        internal static string NoBackOrdersAllowed {
            get {
                return ResourceManager.GetString("NoBackOrdersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backordered items cannot be added to an APF order.
        /// </summary>
        internal static string NoBackOrdersOnAPFOrder {
            get {
                return ResourceManager.GetString("NoBackOrdersOnAPFOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the billing address information required..
        /// </summary>
        internal static string NoBillingAddress {
            get {
                return ResourceManager.GetString("NoBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry you don&apos;t have a registered credit card on file.  Please call Distributor Services at  080-906-7070..
        /// </summary>
        internal static string NoCard {
            get {
                return ResourceManager.GetString("NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out care of name..
        /// </summary>
        internal static string NoCareOfName {
            get {
                return ResourceManager.GetString("NoCareOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot Check Out as your Purchasing Limits have been exceeded.
        /// </summary>
        internal static string NoCheckoutPurchaseLimitsExceeded {
            get {
                return ResourceManager.GetString("NoCheckoutPurchaseLimitsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the city..
        /// </summary>
        internal static string NoCity {
            get {
                return ResourceManager.GetString("NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the county..
        /// </summary>
        internal static string NoCounty {
            get {
                return ResourceManager.GetString("NoCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter courier name..
        /// </summary>
        internal static string NoCourierUpNameEntered {
            get {
                return ResourceManager.GetString("NoCourierUpNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please record a shipping address before you can complete this Pickup Order..
        /// </summary>
        internal static string NoDefaultShippingAddress {
            get {
                return ResourceManager.GetString("NoDefaultShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the delivery date.
        /// </summary>
        internal static string NoDeliveryDateSelected {
            get {
                return ResourceManager.GetString("NoDeliveryDateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear distributor, please call to Distributor Services if there is not any courier available..
        /// </summary>
        internal static string NoDeliveryOption {
            get {
                return ResourceManager.GetString("NoDeliveryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a delivery type.
        /// </summary>
        internal static string NoDeliveryType {
            get {
                return ResourceManager.GetString("NoDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a distributor address..
        /// </summary>
        internal static string NoDistributorAddressEntered {
            get {
                return ResourceManager.GetString("NoDistributorAddressEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t submitted Ethical Form. Please contact Distributor Services for more information.
        /// </summary>
        internal static string NoDistributorNotes {
            get {
                return ResourceManager.GetString("NoDistributorNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address..
        /// </summary>
        internal static string NoEmailAddress {
            get {
                return ResourceManager.GetString("NoEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Express Company for selected Delivery Address.
        /// </summary>
        internal static string NoExpressCompanyForDeliveryAddress {
            get {
                return ResourceManager.GetString("NoExpressCompanyForDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the extension..
        /// </summary>
        internal static string NoExtension {
            get {
                return ResourceManager.GetString("NoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the first name.
        /// </summary>
        internal static string NoFirstName {
            get {
                return ResourceManager.GetString("NoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no items selected to add to the order..
        /// </summary>
        internal static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no items selected to calculate volume..
        /// </summary>
        internal static string NoItemsSelectedToCalculateVolume {
            get {
                return ResourceManager.GetString("NoItemsSelectedToCalculateVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to purchase in the order..
        /// </summary>
        internal static string NoItemToPurchase {
            get {
                return ResourceManager.GetString("NoItemToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the last name..
        /// </summary>
        internal static string NoLastName {
            get {
                return ResourceManager.GetString("NoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processing of your recent Member application may take 12-18 hours.  After your application has been processed you will be able to place orders.  Please check back later to complete your order.
        /// </summary>
        internal static string NoMemberFoundInHMS {
            get {
                return ResourceManager.GetString("NoMemberFoundInHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Product can be added to a Standalone APF order.
        /// </summary>
        internal static string NoNonProductToStandaloneAPF {
            get {
                return ResourceManager.GetString("NoNonProductToStandaloneAPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As there are no Products with your APF order, all non-Product items have been removed..
        /// </summary>
        internal static string NonProductItemsRemovedForStandaloneAPF {
            get {
                return ResourceManager.GetString("NonProductItemsRemovedForStandaloneAPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can only place orders in U.S. or Puerto Rico..
        /// </summary>
        internal static string NonUSPR {
            get {
                return ResourceManager.GetString("NonUSPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a order type..
        /// </summary>
        internal static string NoOrder {
            get {
                return ResourceManager.GetString("NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payment info..
        /// </summary>
        internal static string NoPaymentInfo {
            get {
                return ResourceManager.GetString("NoPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the phone number..
        /// </summary>
        internal static string NoPhone {
            get {
                return ResourceManager.GetString("NoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the pickup date.
        /// </summary>
        internal static string NoPickUpDateSelected {
            get {
                return ResourceManager.GetString("NoPickUpDateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location..
        /// </summary>
        internal static string NoPickUpLocation {
            get {
                return ResourceManager.GetString("NoPickUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a pickup name.
        /// </summary>
        internal static string NoPickUpNameEntered {
            get {
                return ResourceManager.GetString("NoPickUpNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter recipients .
        /// </summary>
        internal static string NoPickUpNameEnteredFor7_11 {
            get {
                return ResourceManager.GetString("NoPickUpNameEnteredFor7-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the pickup phone.
        /// </summary>
        internal static string NoPickUpPhoneEntered {
            get {
                return ResourceManager.GetString("NoPickUpPhoneEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select other Pick Up seleccion.
        /// </summary>
        internal static string NoPickupSelectedAllowed {
            get {
                return ResourceManager.GetString("NoPickupSelectedAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the pickup time.
        /// </summary>
        internal static string NoPickUpTimeSelected {
            get {
                return ResourceManager.GetString("NoPickUpTimeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the province..
        /// </summary>
        internal static string NoProvince {
            get {
                return ResourceManager.GetString("NoProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an RG Number.
        /// </summary>
        internal static string NoRGNumberSelected {
            get {
                return ResourceManager.GetString("NoRGNumberSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Shipping Method.
        /// </summary>
        internal static string NoShippingMethodSelected {
            get {
                return ResourceManager.GetString("NoShippingMethodSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Shipping Time.
        /// </summary>
        internal static string NoShippingTimeSelected {
            get {
                return ResourceManager.GetString("NoShippingTimeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out SMS Mobile Number..
        /// </summary>
        internal static string NoSMSNumber {
            get {
                return ResourceManager.GetString("NoSMSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the state..
        /// </summary>
        internal static string NoState {
            get {
                return ResourceManager.GetString("NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the street address field..
        /// </summary>
        internal static string NoStreet1 {
            get {
                return ResourceManager.GetString("NoStreet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the street 2 address field..
        /// </summary>
        internal static string NoStreet2 {
            get {
                return ResourceManager.GetString("NoStreet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the street 3 address field..
        /// </summary>
        internal static string NoStreet3 {
            get {
                return ResourceManager.GetString("NoStreet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the street 4 address field..
        /// </summary>
        internal static string NoStreet4 {
            get {
                return ResourceManager.GetString("NoStreet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Sub District..
        /// </summary>
        internal static string NoSubDistrict {
            get {
                return ResourceManager.GetString("NoSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Suburb..
        /// </summary>
        internal static string NoSuburb {
            get {
                return ResourceManager.GetString("NoSuburb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have Today Magazine alone with APF. The magazines have been removed from your cart..
        /// </summary>
        internal static string NoTodayMagazineWithStandalonAPF {
            get {
                return ResourceManager.GetString("NoTodayMagazineWithStandalonAPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the zip code..
        /// </summary>
        internal static string NoZipCode {
            get {
                return ResourceManager.GetString("NoZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      This Mexico English ordering site is available for Members who are qualified to attend the Honors 2016 Event in Cancun, Mexico. If you wish to purchase products from Herbalife Mexico, please visit 
        ///      &lt;a href=&quot;https://mx.myherbalife.com&quot;  target=&quot;_blank&quot; &gt;mx.myherbalife.com&lt;/a&gt; . If you have any questions please contact your local Member Services Team.
        ///    .
        /// </summary>
        internal static string NQSMessage {
            get {
                return ResourceManager.GetString("NQSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Authorization was not successful. Please review your cards..
        /// </summary>
        internal static string OneOrMoreCardsWereDeclined {
            get {
                return ResourceManager.GetString("OneOrMoreCardsWereDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the credit cards for your order has not been approved. Herbalife requested reversal of the transactions. However it can take up to 30 business days for the credit to show up on your card statement.
        /// </summary>
        internal static string OneOrMoreCardsWereDeclinedForMultiplecards {
            get {
                return ResourceManager.GetString("OneOrMoreCardsWereDeclinedForMultiplecards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you select &quot;Pick-up&quot; as your delivery method..
        /// </summary>
        internal static string OnlyPickUpAllowed {
            get {
                return ResourceManager.GetString("OnlyPickUpAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you select &quot;Shipping&quot; as your delivery method..
        /// </summary>
        internal static string OnlyShippingAllowed {
            get {
                return ResourceManager.GetString("OnlyShippingAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id:.
        /// </summary>
        internal static string OrderIdForMail {
            get {
                return ResourceManager.GetString("OrderIdForMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed the order month for this order to {month}. Do you wish to continue with this selection?  (&quot;Yes&quot; or &quot;No&quot;).
        /// </summary>
        internal static string OrderMonthChangedByUser {
            get {
                return ResourceManager.GetString("OrderMonthChangedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The OrderMonth has changed!).
        /// </summary>
        internal static string OrderMonthHasFlipped {
            get {
                return ResourceManager.GetString("OrderMonthHasFlipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} is currently out of inventory, your quantity is set to 0..
        /// </summary>
        internal static string OutOfInventory {
            get {
                return ResourceManager.GetString("OutOfInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Code:.
        /// </summary>
        internal static string PaymentCode {
            get {
                return ResourceManager.GetString("PaymentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PaymentGatewayTotalAmountInvalid {
            get {
                return ResourceManager.GetString("PaymentGatewayTotalAmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status:.
        /// </summary>
        internal static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check card information..
        /// </summary>
        internal static string PaymenyFail {
            get {
                return ResourceManager.GetString("PaymenyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the pick up location.
        /// </summary>
        internal static string PickUpLocationNotSelected {
            get {
                return ResourceManager.GetString("PickUpLocationNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pickup location you had selected is not longer available, please select a new address.
        /// </summary>
        internal static string PickUpLocationRemoved {
            get {
                return ResourceManager.GetString("PickUpLocationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Pick Up Location.
        /// </summary>
        internal static string PickUpNickNameNotPopulated {
            get {
                return ResourceManager.GetString("PickUpNickNameNotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The locale you’re trying to access is not available for your profile. If you would like to place an order, please go to MyHerbalife in your country of processing..
        /// </summary>
        internal static string PMTypeRestrictOrdering {
            get {
                return ResourceManager.GetString("PMTypeRestrictOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recently placed an identical order on {0}. If you wish to continue with this order, please submit it now. Otherwise, please click Cancel Order..
        /// </summary>
        internal static string PossibleDuplicateOrder {
            get {
                return ResourceManager.GetString("PossibleDuplicateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recently placed an identical order on {0}, order number {1}. If you wish to continue with this order, please submit it now. Otherwise, please click Cancel Order..
        /// </summary>
        internal static string PossibleDuplicateOrderFound {
            get {
                return ResourceManager.GetString("PossibleDuplicateOrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid zip code..
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart should contains either PreOrdering sku or NonPreOrdering sku .
        /// </summary>
        internal static string PreOrderingSku {
            get {
                return ResourceManager.GetString("PreOrderingSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for the items in your cart has changed due to an error. Please re-submit your order..
        /// </summary>
        internal static string PriceChanged {
            get {
                return ResourceManager.GetString("PriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address cannot be deleted..
        /// </summary>
        internal static string PrimaryAddressDeleteNotAllowed {
            get {
                return ResourceManager.GetString("PrimaryAddressDeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to delete your primary card. Please make a different saved card your primary card before you delete this card..
        /// </summary>
        internal static string PrimaryCardDeleteNotAllowed {
            get {
                return ResourceManager.GetString("PrimaryCardDeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Pickup Preference cannot be deleted..
        /// </summary>
        internal static string PrimaryPickupPreferenceDeleteNotAllowed {
            get {
                return ResourceManager.GetString("PrimaryPickupPreferenceDeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Checkout.
        /// </summary>
        internal static string ProceedToCheckout {
            get {
                return ResourceManager.GetString("ProceedToCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enetr Phone Number .
        /// </summary>
        internal static string PuckUpCorierPhoneNumberErrorMessage {
            get {
                return ResourceManager.GetString("PuckUpCorierPhoneNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct quantity for SKU : {0}..
        /// </summary>
        internal static string QuantityIncorrect {
            get {
                return ResourceManager.GetString("QuantityIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in your cart exceed the limit of the volume point. Please remove items of {0} Volume Points to continue with this order.
        /// </summary>
        internal static string RemainingVolumePointExceeds {
            get {
                return ResourceManager.GetString("RemainingVolumePointExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your required Annual Processing fees have been left in your cart..
        /// </summary>
        internal static string RequiredAPFLeftInCart {
            get {
                return ResourceManager.GetString("RequiredAPFLeftInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member hasn’t completed online basic training..
        /// </summary>
        internal static string RequiredELearning {
            get {
                return ResourceManager.GetString("RequiredELearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the mandatory field..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is not permitted,please click &quot;Submit&quot; again. If problem persists, contact the distributor service hotline 080-906-7070..
        /// </summary>
        internal static string Resubmit {
            get {
                return ResourceManager.GetString("Resubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} as the dual order month is this correct?.
        /// </summary>
        internal static string SelectedDualOrderMonthMessage {
            get {
                return ResourceManager.GetString("SelectedDualOrderMonthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all mandatory shipping information..
        /// </summary>
        internal static string ShippingInfoIncomplete {
            get {
                return ResourceManager.GetString("ShippingInfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter shipping instruction..
        /// </summary>
        internal static string ShippingInstructionNoFilled {
            get {
                return ResourceManager.GetString("ShippingInstructionNoFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Shipping Address.
        /// </summary>
        internal static string ShippingNickNameNotPopulated {
            get {
                return ResourceManager.GetString("ShippingNickNameNotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert: SKU {0} will be expired on {1}. Click “OK” to proceed and click “cancel” to delete it from the shopping cart..
        /// </summary>
        internal static string ShortExpirationDate {
            get {
                return ResourceManager.GetString("ShortExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU {0} is not available..
        /// </summary>
        internal static string SKUNotAvailable {
            get {
                return ResourceManager.GetString("SKUNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a full list of product availability, &lt;a href=&quot;/ordering/inventory&quot;  target=&quot;_Blank&quot; &gt; please click here.&lt;/a&gt;.
        /// </summary>
        internal static string SKUNotAvailableBOLink {
            get {
                return ResourceManager.GetString("SKUNotAvailableBOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not qualified at this time to purchase the selected item..
        /// </summary>
        internal static string SKUNotAvailableForNonQualified {
            get {
                return ResourceManager.GetString("SKUNotAvailableForNonQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add this item to your cart..
        /// </summary>
        internal static string SkuNotValid {
            get {
                return ResourceManager.GetString("SkuNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingHeader {
            get {
                return ResourceManager.GetString("SlowMovingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingSku {
            get {
                return ResourceManager.GetString("SlowMovingSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingSkuDescription {
            get {
                return ResourceManager.GetString("SlowMovingSkuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingSkuUnit {
            get {
                return ResourceManager.GetString("SlowMovingSkuUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingTotalQuentityMessagePart1 {
            get {
                return ResourceManager.GetString("SlowMovingTotalQuentityMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlowMovingTotalQuentityMessagePart2 {
            get {
                return ResourceManager.GetString("SlowMovingTotalQuentityMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SMS Number Can&apos;t be Null .
        /// </summary>
        internal static string SMSNotificationErrorMessage {
            get {
                return ResourceManager.GetString("SMSNotificationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error..
        /// </summary>
        internal static string SysError {
            get {
                return ResourceManager.GetString("SysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment total does not match order total..
        /// </summary>
        internal static string TotalNotMatch {
            get {
                return ResourceManager.GetString("TotalNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your buying privileges are currently on hold until the required “Protecting Your Business 101” training is completed. If you wish to complete the training now, please click on the following link:  &lt;a href=&quot;http://10.36.174.134/toolsAndTraining/business/Training/protectingYourBusiness101.htm&quot; target=&quot;_blank&quot;&gt;Link&lt;/a&gt;.
        /// </summary>
        internal static string TrainingMessage {
            get {
                return ResourceManager.GetString("TrainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to complete the training within the next 7 days and proceed with placing your order now, please click &quot;I Agree&quot; to continue shopping..
        /// </summary>
        internal static string TrainingMessageSecond {
            get {
                return ResourceManager.GetString("TrainingMessageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: Your current and future Royalty and Production Bonus earning privileges are currently on hold until the required “Protecting Your Business 101” training is completed. If you wish to complete the training now, please click on the following link : &lt;a href=&quot;http://10.36.173.61/toolsAndTraining/business/Training/protectingYourBusiness101.htm&quot; target=&quot;_blank&quot;&gt; Protecting Your Business 101&lt;/a&gt;.
        /// </summary>
        internal static string TrainingMsgAfterElapsedTime {
            get {
                return ResourceManager.GetString("TrainingMsgAfterElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The “Protecting Your Business 101” training has not yet been completed and is a requirement for all new Supervisors. Completion of the training and quiz with a minimum score of 80 percent is required within 60 days of your qualification date to ensure there are no disruptions to your future Royalty and Production Bonus earning privileges. If you wish to complete the training now, please click on the following link : &lt;a href=&quot;http://10.36.173.61/toolsAndTraining/business/Training/protectingYourBusiness101.ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrainingMsgWithinElapsedTime {
            get {
                return ResourceManager.GetString("TrainingMsgWithinElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important : Protecting Your Business 101 Training.
        /// </summary>
        internal static string TrainingTitle {
            get {
                return ResourceManager.GetString("TrainingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code for the 3D transaction:.
        /// </summary>
        internal static string Transaction3DStatus {
            get {
                return ResourceManager.GetString("Transaction3DStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code:.
        /// </summary>
        internal static string TransactionCode {
            get {
                return ResourceManager.GetString("TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date:.
        /// </summary>
        internal static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is not permitted,please contact the distributor service hotline 080-906-7070..
        /// </summary>
        internal static string TransactionFail {
            get {
                return ResourceManager.GetString("TransactionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Id:.
        /// </summary>
        internal static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Status Code:.
        /// </summary>
        internal static string TransactionStatusCode {
            get {
                return ResourceManager.GetString("TransactionStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to process your order.  Please check your address and try again.  If problem persists please contact Distributor Services (866) 866-4744..
        /// </summary>
        internal static string UnableToPrice {
            get {
                return ResourceManager.GetString("UnableToPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not add the item(s) to the cart since by adding them into the cart, you exceed your volume points limit..
        /// </summary>
        internal static string VolumePointExceeds {
            get {
                return ResourceManager.GetString("VolumePointExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected pickup from WALDOS, there will be limited products to order from..
        /// </summary>
        internal static string WaldosMessage {
            get {
                return ResourceManager.GetString("WaldosMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping to the entered Zip is not supported.
        /// </summary>
        internal static string ZipNotSupported {
            get {
                return ResourceManager.GetString("ZipNotSupported", resourceCulture);
            }
        }
    }
}
