//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PurchasingLimits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchasingLimits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PurchasingLimits", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total amount exceeds your total amount limit of {0}..
        /// </summary>
        internal static string AmountLimitExceeds {
            get {
                return ResourceManager.GetString("AmountLimitExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resale.
        /// </summary>
        internal static string Consignment {
            get {
                return ResourceManager.GetString("Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item SKU:{0} has not been added to the cart since by adding that into the cart, you exceeded your Purchasing Limit..
        /// </summary>
        internal static string DiscountedRetailExceeds {
            get {
                return ResourceManager.GetString("DiscountedRetailExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of the item SKU:{0} can not be increased by {1} because it exceeds your Purchasing Limit..
        /// </summary>
        internal static string DiscountedRetailExceedsByIncreasingQuantity {
            get {
                return ResourceManager.GetString("DiscountedRetailExceedsByIncreasingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item SKU:{0} has not been added to the cart since by adding that into the cart, you exceeded your earnings  limit..
        /// </summary>
        internal static string EarningExceeds {
            get {
                return ResourceManager.GetString("EarningExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of the item SKU:{0} can not be increased by {1} because it exceeds your earnings limit..
        /// </summary>
        internal static string EarningExceedsByIncreasingQuantity {
            get {
                return ResourceManager.GetString("EarningExceedsByIncreasingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order exceeds: {0:F2}, please adjust your shopping cart and then submit the order..
        /// </summary>
        internal static string ErrorMessageToPCWhenhittheFOPLimits {
            get {
                return ResourceManager.GetString("ErrorMessageToPCWhenhittheFOPLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Order Type from the mini cart.
        /// </summary>
        internal static string NeedToSelectOrderType {
            get {
                return ResourceManager.GetString("NeedToSelectOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot Check Out as your Purchasing Limits have been exceeded.
        /// </summary>
        internal static string NoCheckoutPurchaseLimitsExceeded {
            get {
                return ResourceManager.GetString("NoCheckoutPurchaseLimitsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Consumption.
        /// </summary>
        internal static string PersonalConsumption {
            get {
                return ResourceManager.GetString("PersonalConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PostErrorRemainingPurchasingLimitsEarningsSummary {
            get {
                return ResourceManager.GetString("PostErrorRemainingPurchasingLimitsEarningsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PostErrorRemainingPurchasingLimitsVolumeSummary {
            get {
                return ResourceManager.GetString("PostErrorRemainingPurchasingLimitsVolumeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order exceeded the order volume permitted, Volume Points remaining: {0:F2}. The following SKU(s) have not been added to your cart..
        /// </summary>
        internal static string PostErrorRemainingThresholdLimitsVolumeSummary {
            get {
                return ResourceManager.GetString("PostErrorRemainingThresholdLimitsVolumeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t purchase products {0}..
        /// </summary>
        internal static string PurchaseLimitTypeProductCategory {
            get {
                return ResourceManager.GetString("PurchaseLimitTypeProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item SKU:{0} has not been added to the cart since by adding that into the cart, you exceeded your volume points  limit..
        /// </summary>
        internal static string VolumePointExceeds {
            get {
                return ResourceManager.GetString("VolumePointExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of the item SKU:{0} can not be increased by {1} because it exceeds your volume points limit..
        /// </summary>
        internal static string VolumePointExceedsByIncreasingQuantity {
            get {
                return ResourceManager.GetString("VolumePointExceedsByIncreasingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item SKU:{0}..
        /// </summary>
        internal static string VolumePointExceedsThreshold {
            get {
                return ResourceManager.GetString("VolumePointExceedsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of the item SKU:{0} can not be increased by {1} because it exceeds your volume points limit..
        /// </summary>
        internal static string VolumePointExceedsThresholdByIncreasingQuantity {
            get {
                return ResourceManager.GetString("VolumePointExceedsThresholdByIncreasingQuantity", resourceCulture);
            }
        }
    }
}
